
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sushil
 */
public class Admission extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admission
     */
    Connection con;
    public Admission(Connection con) {
        initComponents();
        this.con=con;
      
        
    }
    void fillTable(String classname)
    {
        Vector heading=new Vector();
        heading.add("fee_name");
        heading.add("fee");
        try
        {
            String query="select * from tablehead,classwisedetail where tablehead.fee_id=classwisedetail.fee_id and classwisedetail.class_name=?";
          
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1,classname);
            ResultSet rs=ps.executeQuery();
            Vector data=new Vector();
            while(rs.next())
            {
                Vector row=new Vector();
                String feeid=rs.getString("fee_name");
                String fee=rs.getString("fee");
                row.add(feeid);
                row.add(fee);
                data.add(row);
            }
            DefaultTableModel d=new DefaultTableModel(data,heading);
            jTable1.setModel(d);
            

            TableModel tm=jTable1.getModel();
            int sum=0;
            
            int count=jTable1.getRowCount();
            for(int i=0;i<count;i++)
            {
                String sm=(String)tm.getValueAt(i, 1);
              sum+=Integer.parseInt(sm); 
            }
            
            txtTotal.setText(String.valueOf(sum));
            
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboclassname = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstudentname = new javax.swing.JTextField();
        txtfathername = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        comfrequency = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txapaymentdetail = new javax.swing.JTextArea();
        rcheque = new javax.swing.JRadioButton();
        rcash = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        commonth = new javax.swing.JComboBox<>();
        txtyear = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField4.setText("jTextField4");

        jLabel10.setText("tution fee");

        jLabel11.setText("total");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Admission");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 10, 69, 17);

        jLabel3.setText("Studentid");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 95, 68, 17);
        getContentPane().add(txtstudentid);
        txtstudentid.setBounds(133, 90, 92, 27);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(258, 89, 60, 29);

        jLabel8.setText("class");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 60, 34, 17);

        comboclassname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboclassname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboclassnameItemStateChanged(evt);
            }
        });
        getContentPane().add(comboclassname);
        comboclassname.setBounds(630, 50, 60, 30);

        jLabel9.setText("Annual fees");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(550, 190, 82, 17);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Fee_name", "fee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 230, 452, 173);

        jButton2.setText("Submmit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1050, 420, 73, 29);

        jLabel4.setText("studentname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(21, 179, 94, 17);

        jLabel5.setText("father'sname");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(21, 254, 94, 17);

        jLabel6.setText("D.O.B");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(21, 324, 41, 17);

        jLabel7.setText("Gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(21, 408, 52, 17);
        getContentPane().add(txtstudentname);
        txtstudentname.setBounds(197, 174, 121, 27);
        getContentPane().add(txtfathername);
        txtfathername.setBounds(197, 244, 121, 27);
        getContentPane().add(txtdob);
        txtdob.setBounds(197, 319, 121, 27);

        rmale.setText("male");
        getContentPane().add(rmale);
        rmale.setBounds(162, 404, 60, 24);

        rfemale.setText("female");
        getContentPane().add(rfemale);
        rfemale.setBounds(269, 404, 75, 24);

        jLabel13.setText("total");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(500, 470, 33, 17);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(640, 470, 103, 27);

        jLabel12.setText("date");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(960, 90, 32, 17);
        getContentPane().add(txtdate);
        txtdate.setBounds(1130, 90, 90, 27);

        jLabel14.setText("frequency");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(960, 160, 72, 17);

        comfrequency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Annualy", "Monthly", " " }));
        getContentPane().add(comfrequency);
        comfrequency.setBounds(1129, 150, 90, 27);

        jLabel15.setText("payment mode");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(960, 230, 104, 17);

        jLabel16.setText("payment detail");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(960, 310, 103, 30);

        txapaymentdetail.setColumns(20);
        txapaymentdetail.setRows(5);
        jScrollPane2.setViewportView(txapaymentdetail);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1130, 300, 140, 60);

        buttonGroup1.add(rcheque);
        rcheque.setText("cheque");
        getContentPane().add(rcheque);
        rcheque.setBounds(1100, 230, 79, 24);

        buttonGroup1.add(rcash);
        rcash.setText("cash");
        getContentPane().add(rcash);
        rcash.setBounds(1200, 230, 90, 24);

        jLabel17.setText("Month");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(510, 100, 70, 30);

        jLabel18.setText("Year");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(600, 110, 57, 17);

        commonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        getContentPane().add(commonth);
        commonth.setBounds(500, 140, 80, 27);
        getContentPane().add(txtyear);
        txtyear.setBounds(580, 140, 150, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String studentid=txtstudentid.getText();
       try
       {
           String query="select studentname,fathername,dob,gender from studentdata where studentid=?";
           PreparedStatement ps=con.prepareStatement(query);
           ps.setString(1,studentid);
           ResultSet rs=ps.executeQuery();
           while(rs.next())
           {
               String name=rs.getString("studentname");
               String fname=rs.getString("fathername");
               String dob=rs.getString("dob");
               String gender=rs.getString("gender");
           
           txtstudentname.setText(name);
           txtfathername.setText(fname);
           txtdob.setText(dob);
           if(gender.equalsIgnoreCase("male"))
           {
               rmale.setSelected(true);
           }
           else
           {
               rfemale.setSelected(true);
           }
           }
         
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String studentid=txtstudentid.getText();
        String classname=(String)comboclassname.getSelectedItem();
        String totalamount=txtTotal.getText();
        String date=txtdate.getText();
        String frequency=(String)comfrequency.getSelectedItem();
        String paymentdetail=txapaymentdetail.getText();
        String paymentmode="";
        if(rcheque.isSelected())
        {
            paymentmode="cheque";
        }
        else
        {
            paymentmode="cash";
        }
        String month=(String)commonth.getSelectedItem();
        String year=txtyear.getText();
       try
       {
           String query="insert into studentfee(studentid,class_name,total_amount,date,frequency,paymentmode,paymentdetail,month,year) values(?,?,?,?,?,?,?,?,?)";
           PreparedStatement ps=con.prepareStatement(query);
           ps.setString(1,studentid);
           ps.setString(2,classname);
           ps.setString(3,totalamount);
           ps.setString(4,date);
           ps.setString(5,frequency);
           ps.setString(6,paymentmode);
           ps.setString(7,paymentdetail);
           ps.setString(8,month);
           ps.setString(9,year);
           
           int count=ps.executeUpdate();
           
           JOptionPane.showMessageDialog(this,count+"save");
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboclassnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboclassnameItemStateChanged
        String classname=(String)comboclassname.getSelectedItem();
        
        fillTable(classname);
    }//GEN-LAST:event_comboclassnameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboclassname;
    private javax.swing.JComboBox<String> comfrequency;
    private javax.swing.JComboBox<String> commonth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton rcash;
    private javax.swing.JRadioButton rcheque;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTextArea txapaymentdetail;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfathername;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentname;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
