
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sushil
 */
public class Monthly extends javax.swing.JInternalFrame {

    /**
     * Creates new form Annualy
     */
    Connection con;
    public Monthly(Connection con) {
        initComponents();
        this.con=con;
        
        txtfreq.setText("Monthly");
        //txtfreq.setText("year");
        
       
    }
     void fillTable(String classname)
    {
        Vector heading=new Vector();
        heading.add("fee_name");
        heading.add("fee");
        try
        {
             String query="select * from tablehead,classwisedetail where tablehead.fee_id=classwisedetail.fee_id and classwisedetail.class_name=? and tablehead.frequency='monthly'";
          
            PreparedStatement ps=con.prepareStatement(query);
          
           ps.setString(1,classname);
            ResultSet rs=ps.executeQuery();
            Vector data=new Vector();
            while(rs.next())
            {
                Vector row=new Vector();
                String feename=rs.getString("fee_name");
                String fee=rs.getString("fee");
                row.add(feename);
                row.add(fee);
                data.add(row);
            }
            DefaultTableModel d=new DefaultTableModel(data,heading);
            jTable1.setModel(d);
            

            TableModel tm=jTable1.getModel();
            int sum=0;
            
            int count=jTable1.getRowCount();
            for(int i=0;i<count;i++)
            {
                String sm=(String)tm.getValueAt(i, 1);
              sum+=Integer.parseInt(sm); 
            }
            
            txtTotal.setText(String.valueOf(sum));
            
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfreq = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtmonth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboclassname = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtstudentname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfathername = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        compayment = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txapaymentdetail = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Monthly");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(191, 30, 57, 17);

        jLabel2.setText("Frequency");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(66, 84, 74, 17);

        jLabel3.setText("Month");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(77, 152, 46, 17);
        getContentPane().add(txtfreq);
        txtfreq.setBounds(253, 79, 128, 27);

        txtyear.setText("2018");
        getContentPane().add(txtyear);
        txtyear.setBounds(309, 147, 110, 27);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "fee_name", "fee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 90, 340, 179);

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1010, 370, 119, 40);

        jLabel4.setText("Total");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 307, 36, 20);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal);
        txtTotal.setBounds(700, 310, 117, 27);

        txtmonth.setText("JAN");
        getContentPane().add(txtmonth);
        txtmonth.setBounds(259, 147, 38, 27);

        jLabel5.setText("class");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 30, 49, 17);

        comboclassname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboclassname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboclassnameItemStateChanged(evt);
            }
        });
        getContentPane().add(comboclassname);
        comboclassname.setBounds(680, 30, 83, 27);

        jLabel6.setText("Studentid");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 250, 68, 17);

        jLabel7.setText("Student_name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 330, 102, 17);
        getContentPane().add(txtstudentid);
        txtstudentid.setBounds(210, 250, 110, 27);

        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 250, 59, 29);
        getContentPane().add(txtstudentname);
        txtstudentname.setBounds(210, 330, 110, 27);

        jLabel8.setText("Father'name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 410, 89, 17);

        jLabel9.setText("D.O.B");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 490, 41, 17);

        jLabel10.setText("Gender");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 560, 52, 17);
        getContentPane().add(txtfathername);
        txtfathername.setBounds(210, 410, 110, 27);
        getContentPane().add(txtdob);
        txtdob.setBounds(210, 480, 110, 27);

        buttonGroup1.add(rmale);
        rmale.setText("male");
        getContentPane().add(rmale);
        rmale.setBounds(180, 560, 60, 24);

        buttonGroup1.add(rfemale);
        rfemale.setText("female");
        rfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rfemale);
        rfemale.setBounds(180, 610, 123, 20);

        jLabel11.setText("date");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(940, 60, 32, 17);

        jLabel12.setText("payment mode");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(940, 140, 104, 17);

        jLabel13.setText("payment detail");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(940, 240, 103, 17);
        getContentPane().add(txtdate);
        txtdate.setBounds(1040, 50, 110, 27);

        compayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "cheque", "cash" }));
        getContentPane().add(compayment);
        compayment.setBounds(1090, 130, 90, 27);

        txapaymentdetail.setColumns(20);
        txapaymentdetail.setRows(5);
        jScrollPane2.setViewportView(txapaymentdetail);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1070, 210, 160, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String month=txtmonth.getText();
        String year=txtyear.getText();
        String studentid=txtstudentid.getText();
        String classname=(String)comboclassname.getSelectedItem();
        String date=txtdate.getText();
        String paymentdetail=txapaymentdetail.getText();
        String payment_mode=(String)compayment.getSelectedItem();
        String totalamount=txtTotal.getText();
        String frequency=txtfreq.getText();
        try
        {
            String query="insert into studentfee(month,year,studentid,class_name,date,paymentdetail,paymentmode,total_amount,frequency) values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1,month);
            ps.setString(2,year);
            ps.setString(3,studentid);
            ps.setString(4,classname);
            ps.setString(5,date);
            ps.setString(6,paymentdetail);
            ps.setString(7,payment_mode);
            ps.setString(8,totalamount);
            ps.setString(9,frequency);
            
            int count=ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this,count+"save");
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void rfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfemaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String studentid=txtstudentid.getText();
       try
       {
           String query="select studentname,fathername,dob,gender from studentdata where studentid=?";
           PreparedStatement ps=con.prepareStatement(query);
           ps.setString(1,studentid);
           ResultSet rs=ps.executeQuery();
           while(rs.next())
           {
               String name=rs.getString("studentname");
               String fname=rs.getString("fathername");
               String dob=rs.getString("dob");
               String gender=rs.getString("gender");
           
           txtstudentname.setText(name);
           txtfathername.setText(fname);
           txtdob.setText(dob);
           if(gender.equalsIgnoreCase("male"))
           {
               rmale.setSelected(true);
           }
           else
           {
               rfemale.setSelected(true);
           }
           }
         
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboclassnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboclassnameItemStateChanged
         String classname=(String)comboclassname.getSelectedItem();
        
        fillTable(classname);
    }//GEN-LAST:event_comboclassnameItemStateChanged
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboclassname;
    private javax.swing.JComboBox<String> compayment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTextArea txapaymentdetail;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfathername;
    private javax.swing.JTextField txtfreq;
    private javax.swing.JTextField txtmonth;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentname;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
