
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sushil
 */
public class studentdata extends javax.swing.JInternalFrame {

    /**
     * Creates new form studentdata
     */
    Connection con;
    String studentid;
    public studentdata(Connection con) {
        initComponents();
        
        this.con=con;
        fillTable();
    }
    
    void fillTable()
    {
        Vector heading=new Vector();
        heading.add("Student_id");
        heading.add("Student_name");
        heading.add("Father's_name");
        heading.add("Mother's_name");
        heading.add("D.O.B");
        heading.add("Gender");
        heading.add("Contact1");
        heading.add("Contact2");
        heading.add("Address");
        
        try
        {
            String query="select * from studentdata";
            PreparedStatement ps=con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            Vector data=new Vector();
            while(rs.next())
            {
                Vector row=new Vector();
                String studentid=rs.getString("studentid");
                String studentname=rs.getString("studentname");
                String fathername=rs.getString("fathername");
                String mothername=rs.getString("mothername");
                String dob=rs.getString("dob");
                String contact1=rs.getString("contact1");
                String contact2=rs.getString("contact2");
                String address=rs.getString("address");
                
                row.add(studentid);
                row.add(studentname);
                row.add(fathername);
                row.add(mothername);
                row.add(dob);
                row.add(contact1);
                row.add(contact2);
                row.add(address);
                data.add(row);
                
            }
            DefaultTableModel d=new DefaultTableModel(data,heading);
            jTable1.setModel(d);
                    
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtstudentname = new javax.swing.JTextField();
        txtfathername = new javax.swing.JTextField();
        txtmothername = new javax.swing.JTextField();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        txtcontact1 = new javax.swing.JTextField();
        txtcontact2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaaddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtdob = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jLabel11.setText("Student_id");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Student_info");

        jLabel3.setText("Student_name");

        jLabel4.setText("Father's_name");

        jLabel5.setText("Mother'_name");

        jLabel6.setText("D.O.B");

        jLabel7.setText("Gender");

        jLabel8.setText("Contact1");

        jLabel9.setText("Contact2");

        jLabel10.setText("Address");

        txtmothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmothernameActionPerformed(evt);
            }
        });

        buttonGroup1.add(rmale);
        rmale.setText("male");

        buttonGroup1.add(rfemale);
        rfemale.setText("female");

        txtcontact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontact1ActionPerformed(evt);
            }
        });

        txtcontact2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontact2ActionPerformed(evt);
            }
        });

        txaaddress.setColumns(20);
        txaaddress.setRows(5);
        jScrollPane1.setViewportView(txaaddress);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_name", "Student_id", "Father's_name", "Mother's_name", "D.O.B", "Gender", "Contact1", "Contact2", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(rmale)
                                    .addGap(40, 40, 40)
                                    .addComponent(rfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(161, 161, 161)
                                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(147, 147, 147)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtcontact1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtcontact2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(54, 54, 54)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(107, 107, 107)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(253, 253, 253))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addGap(135, 135, 135)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtmothername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(681, 681, 681)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(90, 90, 90)
                                .addComponent(jButton3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfathername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtmothername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rmale)
                            .addComponent(rfemale))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtcontact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcontact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmothernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmothernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmothernameActionPerformed

    private void txtcontact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontact1ActionPerformed

    private void txtcontact2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontact2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontact2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String studentname=txtstudentname.getText();
        String fathername=txtfathername.getText();
        String mothername=txtmothername.getText();
        String dob=txtdob.getText();
         String gender="";
        if(rmale.isSelected())
        {
            gender="male";
            
        }
        else
        {
            gender="female";
        }
        String contact1=txtcontact1.getText();
        String contact2=txtcontact2.getText();
        String address=txaaddress.getText();
       
        
        try
        {
            String query="insert into studentdata(studentname,fathername,mothername,dob,gender,contact1,contact2,address) values(?,?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(query);
                 
            ps.setString(1,studentname);
            ps.setString(2,fathername);
            ps.setString(3,mothername);
            ps.setString(4,dob);
            ps.setString(5,gender);
            ps.setString(6,contact1);
            ps.setString(7,contact2);
            ps.setString(8,address);
            
            int count=ps.executeUpdate();
            JOptionPane.showMessageDialog(this,count+"data inserted");
            fillTable();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        String studentname=txtstudentname.getText();
        String fathername=txtfathername.getText();
        String mothername=txtmothername.getText();
        String dob=txtdob.getText();
        String contact1=txtcontact1.getText();
        String contact2=txtcontact2.getText();
        String address=txaaddress.getText();
        String gender="";
        if(rmale.isSelected())
        {
            gender="male";
            
        }
        else
        {
            gender="female";
        }
        try
        {
            String query="update student set studentname=?,fathername=?,mothername=?,dob=?,gender=?,contact1=?,contact2=?,address=? where studentid=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1,studentname);
            ps.setString(2,fathername);
            ps.setString(3,mothername);
            ps.setString(4,dob);
            ps.setString(5,gender);
            ps.setString(6,contact1);
            ps.setString(7,contact2);
            ps.setString(8,address);
            ps.setString(9,studentid);
            
            int count=ps.executeUpdate();
            JOptionPane.showMessageDialog(this,count+"data updated");
            fillTable();
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        String studentname=txtstudentname.getText();
        String fathername=txtfathername.getText();
        String mothername=txtmothername.getText();
        String dob=txtdob.getText();
        String contact1=txtcontact1.getText();
        String contact2=txtcontact2.getText();
        String address=txaaddress.getText();
        String gender="";
        if(rmale.isSelected())
        {
            gender="male";
            
        }
        else
        {
            gender="female";
        }
        try
        {
            String query="delete from studentdata where studentid=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1,studentid);
            
            int count=ps.executeUpdate();
            JOptionPane.showMessageDialog(this,count+"data deleted");
            fillTable();
        }
        catch(Exception e)
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       TableModel tm=jTable1.getModel();
      int row=jTable1.getSelectedRow();
      
      
    studentid=(String)tm.getValueAt(row, 0);
       String studentname=(String)tm.getValueAt(row, 1);
         String fathername=(String)tm.getValueAt(row, 2);
           String mothername=(String)tm.getValueAt(row, 3);
             String dob=(String)tm.getValueAt(row, 4);
               String gender=(String)tm.getValueAt(row, 5);
                 String contact1=(String)tm.getValueAt(row, 6); 
                 String contact2=(String)tm.getValueAt(row,7);
                 String address=(String)tm.getValueAt(row,8);
        
        txtstudentid.setText(studentid);
        txtstudentname.setText(studentname);
        txtfathername.setText(fathername);
        txtmothername.setText(mothername);
        txtdob.setText(dob);
        txtcontact1.setText(contact1);
        txtcontact2.setText(contact2);
        txaaddress.setText(address);
        
        
        if(gender.equalsIgnoreCase("male"))
        {
            rmale.setSelected(true);
        }
        else
        {
            rfemale.setSelected(true);
        }
      
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTextArea txaaddress;
    private javax.swing.JTextField txtcontact1;
    private javax.swing.JTextField txtcontact2;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfathername;
    private javax.swing.JTextField txtmothername;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentname;
    // End of variables declaration//GEN-END:variables
}
